# Generated by Django 3.2.6 on 2023-05-31 08:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default=datetime.datetime(2023, 5, 31, 8, 34, 48, 137781, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
